// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;
using Cratis.Cli.Commands.LlmContext;

namespace Cratis.Cli.Commands.Init;

/// <summary>
/// Generates AI skill files containing the full Chronicle CLI command reference.
/// </summary>
/// <remarks>
/// Produces a file that follows the AI skill convention used by GitHub Copilot
/// (.github/skills/&lt;name&gt;/SKILL.md) and the equivalent Claude slash command convention.
/// The file embeds both the JSON Schema for the llm-context format and the live
/// command descriptor so AI agents can look up exact command names and options on demand.
/// </remarks>
public static class ChronicleSkillGenerator
{
    /// <summary>
    /// Gets the skill name used in YAML frontmatter and file paths.
    /// </summary>
    public const string SkillName = "chronicle-cli";

    /// <summary>
    /// Generates the skill file content for the given llm-context JSON.
    /// </summary>
    /// <param name="llmContextJson">Serialized output of <c>cratis llm-context</c>.</param>
    /// <returns>Full skill file content including YAML frontmatter and markdown body.</returns>
    public static string Generate(string llmContextJson)
    {
        var sb = new StringBuilder();
        sb.AppendLine("---")
            .AppendLine($"name: {SkillName}")
            .AppendLine("description: Full Chronicle CLI command reference. Load this skill when writing cratis commands, diagnosing Chronicle issues, or exploring CLI capabilities. Contains all command groups, options, arguments, and output guidance as a machine-readable JSON descriptor.")
            .AppendLine("---")
            .AppendLine()
            .AppendLine("# Chronicle CLI Command Reference")
            .AppendLine()
            .AppendLine("Generated by `cratis init`. Run `cratis init --refresh` to update the embedded command catalog.")
            .AppendLine()
            .AppendLine("## How to Use")
            .AppendLine()
            .AppendLine("Look up exact command names, options, and arguments in the **Command Reference** section.")
            .AppendLine("Use `--output plain` for human-readable list output and `--output json-compact` for structured data.")
            .AppendLine()
            .AppendLine("## JSON Schema")
            .AppendLine()
            .AppendLine("The following schema describes the structure of the Command Reference section:")
            .AppendLine()
            .AppendLine("```json")
            .AppendLine(LlmContextCommand.JsonSchema.Trim())
            .AppendLine("```")
            .AppendLine()
            .AppendLine("## Command Reference")
            .AppendLine()
            .AppendLine("```json")
            .AppendLine(llmContextJson)
            .AppendLine("```");
        return sb.ToString();
    }
}
