// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

using System.Text;

namespace Cratis.Cli.Commands.Init;

/// <summary>
/// Generates the CHRONICLE.md reference document for AI agents.
/// </summary>
public static class ChronicleDocGenerator
{
    /// <summary>
    /// Generates the full CHRONICLE.md content.
    /// </summary>
    /// <returns>The document content as a string.</returns>
    public static string Generate()
    {
        var version = typeof(Program).Assembly.GetName().Version?.ToString() ?? "0.0.0";
        var sb = new StringBuilder();

        sb.AppendLine("# Chronicle CLI Reference")
            .AppendLine()
            .AppendLine($"Generated by `cratis init` (CLI v{version}). Run `cratis init --refresh` to update.")
            .AppendLine()
            .AppendLine("## What is Chronicle?")
            .AppendLine()
            .AppendLine("Chronicle is an event-sourced system built by Cratis. It stores domain events in append-only event sequences,")
            .AppendLine("projects them into read models via observers (reactors, reducers, projections), and provides a gRPC API for management.")
            .AppendLine("The `cratis` CLI connects to a Chronicle server to inspect and manage event stores, observers, projections, and more.")
            .AppendLine()
            .AppendLine("## Connection Setup")
            .AppendLine()
            .AppendLine("The CLI resolves the server connection in this order:")
            .AppendLine("1. `--server` flag")
            .AppendLine("2. `CHRONICLE_CONNECTION_STRING` environment variable")
            .AppendLine("3. Active context in `<home>/.cratis/config.json` — run `cratis context path` to see the resolved path on your system")
            .AppendLine("4. Default: `chronicle://localhost:35000`")
            .AppendLine()
            .AppendLine("```bash")
            .AppendLine("# Create a named context")
            .AppendLine("cratis context create dev --server chronicle://localhost:35000/?disableTls=true")
            .AppendLine("cratis context set dev")
            .AppendLine("```")
            .AppendLine()
            .AppendLine("## Output Format Guidance")
            .AppendLine()
            .AppendLine("- Use `--output plain` for list commands that return large payloads (up to 34x fewer tokens than JSON).")
            .AppendLine("- Use `--output json-compact` when you need structured data with fewer tokens than `json`.")
            .AppendLine("- Use `--quiet` (`-q`) to get only IDs for piping: `cratis observers list -q | xargs -I {} cratis observers replay {} -y`")
            .AppendLine("- Use `--yes` (`-y`) to skip confirmation prompts in scripts and automation.")
            .AppendLine("- JSON errors include a machine-parseable `error` code alongside the human-readable `message` field.")
            .AppendLine()
            .AppendLine("## Troubleshooting Decision Tree")
            .AppendLine()
            .AppendLine("### Cannot connect to server")
            .AppendLine("1. Run `cratis version -o json` — check if server version appears.")
            .AppendLine("2. Check connection string: `cratis config show -o json`.")
            .AppendLine("3. Verify server is running and reachable on the configured port.")
            .AppendLine()
            .AppendLine("### Observer stuck or behind")
            .AppendLine("1. Run `cratis observers list -o plain` — check observer state and sequence numbers.")
            .AppendLine("2. Run `cratis observers show <id> -o json` — inspect detailed state.")
            .AppendLine("3. Check failed partitions: `cratis failed-partitions list -o plain`.")
            .AppendLine("4. If a partition is failing, inspect: `cratis failed-partitions show <observer-id> <partition>`.")
            .AppendLine("5. Fix the underlying issue, then retry: `cratis observers retry-partition <observer-id> <partition> -y`.")
            .AppendLine("6. To replay from scratch: `cratis observers replay <observer-id> -y`.")
            .AppendLine()
            .AppendLine("### Data not appearing in read model")
            .AppendLine("1. Verify events exist: `cratis events has <event-source-id>`.")
            .AppendLine("2. Check the projection observer is running: `cratis observers list --type projection -o plain`.")
            .AppendLine("3. Check read model instances: `cratis read-models instances <name>`.")
            .AppendLine("4. Check for failed partitions on the projection observer.")
            .AppendLine()
            .AppendLine("## Safety Notes")
            .AppendLine()
            .AppendLine("- Replay and retry commands are destructive (they re-process events). Always confirm before running.")
            .AppendLine("- Use `--yes` only in automation with proper safeguards.")
            .AppendLine("- Remove commands (users, applications) are irreversible.")
            .AppendLine()
            .AppendLine("## Command Reference")
            .AppendLine()
            .AppendLine("The full command catalog is available as an AI skill — load it on demand when you need exact command names, options, or arguments:")
            .AppendLine()
            .AppendLine("- **GitHub Copilot**: invoke the `chronicle-cli` skill")
            .AppendLine("- **Claude Code**: run the `/chronicle-cli` slash command")
            .AppendLine("- **Any tool**: run `cratis llm-context` for a live JSON dump, or `cratis llm-context --schema` for the JSON Schema");

        return sb.ToString();
    }
}
